# Generated by Django 5.0.3 on 2024-03-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='twitter_card',
        ),
        migrations.AddField(
            model_name='song',
            name='meta_tags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metatags'),
        ),
    ]
