# Generated by Django 5.0.3 on 2024-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analyzedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='json_ld',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
