# Generated by Django 5.0.3 on 2024-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_analyzedimage_alt_alter_analyzedimage_json_ld'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('prompt', models.TextField(default="Generate a JSON-LD using a schema from schema.org that is most appropriate for this JSON data: {data} Your response should only be the JSON-LD as a string and nothing else, which should start with '{' and end with '}'.")),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='json_ld',
        ),
        migrations.RemoveField(
            model_name='song',
            name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='song',
            name='seo_content',
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='JSON_LD',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
