# Generated by Django 5.0.3 on 2024-03-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jsonld_remove_song_json_ld_remove_song_meta_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatags',
            name='prompt',
            field=models.TextField(default="Generate a dictionary with keys and values that could consist the Basic HTML Meta Tags. Based on the data model below. The value of description must have about 150 words. Your response should only be a dictionary starting with only one '{' , ending with only one '}', without any comments, without null values, and both keys and values using double quotes. The dictionary should contain more than 20 pairs of key-value, but should not include any og tags (key-value pairs starting with 'og')."),
        ),
        migrations.AlterField(
            model_name='jsonld',
            name='prompt',
            field=models.TextField(default="Generate a JSON-LD using a schema from schema.org that is most appropriate for the JSON data provided below. Your response should only be the JSON-LD as a string and nothing else, which should start with '{' and end with '}'."),
        ),
    ]
