# Generated by Django 5.0.3 on 2024-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jsonld_prompt_alter_metatags_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='opengraph',
            name='prompt',
            field=models.TextField(default="Generate a dictionary, with keys are name and value are the content that are appropriate for a Facebook card which also know OpenGraph html block , using the serialized data below. Your response should only be a dictionary start with only one '{' , end with only one  '}' , based on ogp.me, the dictionary do not include any comments,and None value.  both keys and values using double quote.    And og:title, og:type og:image og:url are 4 required properties for every page . and You response as much as possible, but dont impute any value except the 4 properties above which are not in the serialized data."),
        ),
        migrations.AlterField(
            model_name='opengraph',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
