# Generated by Django 5.0.3 on 2024-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_opengraph_prompt_alter_opengraph_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocontent',
            name='prompt',
            field=models.TextField(default='Generate SEO content based off of the instance data.\n            The content must include one H1 tag that contains the most relevant keywords in the instance data.\n            The content generated must contain at least one H2 tag.\n            The content must include at least 500 total words of content separated in as many paragraph tags as necessary and divided into whatever heading structure necessary.\n            The LLM output should be in a valid HTML format using heading tags and paragraph tags only.\n            Here is the instance data: '),
        ),
        migrations.AddField(
            model_name='twittercard',
            name='prompt',
            field=models.TextField(default="Generate a dictionary, with keys as the names and values as the content that are appropriate for a Twitter card HTML block, using the serialized data below. Your response should only be a dictionary starting with only one '{' and ending with only one '}', without any comments, without null values, and both keys and values using double quotes."),
        ),
        migrations.AlterField(
            model_name='seocontent',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='twittercard',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
