# Generated by Django 5.0.3 on 2024-03-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_jsonld_remove_song_json_ld_remove_song_meta_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.analyzedimage')),
                ('json_ld', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jsonld')),
                ('meta_tags', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metatags')),
                ('open_graph', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.opengraph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('json_ld', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jsonld')),
                ('seo_content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seocontent')),
                ('twitter_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.twittercard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
