from .gemini import generate_content


def generate_json_ld(instance):
    # serialized_instance
    # prompt = "Generate a json ld using a schema from schema.org that is most appropriate for this jsno data: " + serialized_instance. Your respones hould only be the json_ld as as tring and nothing else.

    json_ld = generate_content(
        "generate a json ld based off of the instanance " + instance_info)
    return {"data": "generated by AI"}


def generate_meta_tags(instance):
    pass


def generate_open_graph(instance):
    pass


def generate_twitter_card(instance):
    data = instance.json_ld.data
    return data
